# Generated by Django 4.2.7 on 2023-11-29 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_manufacturer_offer_store_testcomponent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('processor', 'Процессор'), ('motherboard', 'Материнская плата'), ('graphics_card', 'Видеокарта'), ('ram', 'ОЗУ'), ('cooler', 'Кулер'), ('case_fan', 'Вентилятор'), ('liquid_cooling', 'Жидкостное охлаждение'), ('case', 'Корпус'), ('hdd', 'Диск HDD'), ('ssd', 'Диск SSD'), ('ssdm2', 'Диск SSDM2'), ('power_supply', 'Блок питания')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aggregator.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('component_type', models.CharField(choices=[('processor', 'Процессор'), ('motherboard', 'Материнская плата'), ('graphics_card', 'Видеокарта'), ('ram', 'ОЗУ'), ('cooler', 'Кулер'), ('case_fan', 'Вентилятор'), ('liquid_cooling', 'Жидкостное охлаждение'), ('case', 'Корпус'), ('hdd', 'Диск HDD'), ('ssd', 'Диск SSD'), ('ssdm2', 'Диск SSDM2'), ('power_supply', 'Блок питания')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='casefan',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='cooler',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='graphicscard',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='hdd',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='liquidcooling',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='powersupply',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='ssd',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='ssdm2',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='testcomponent',
            name='manufacturer',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='CaseFan',
        ),
        migrations.DeleteModel(
            name='Cooler',
        ),
        migrations.DeleteModel(
            name='GraphicsCard',
        ),
        migrations.DeleteModel(
            name='HDD',
        ),
        migrations.DeleteModel(
            name='LiquidCooling',
        ),
        migrations.DeleteModel(
            name='Motherboard',
        ),
        migrations.DeleteModel(
            name='PowerSupply',
        ),
        migrations.DeleteModel(
            name='Processor',
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
        migrations.DeleteModel(
            name='SSD',
        ),
        migrations.DeleteModel(
            name='SSDM2',
        ),
        migrations.DeleteModel(
            name='TestComponent',
        ),
        migrations.AddField(
            model_name='component',
            name='properties',
            field=models.ManyToManyField(to='aggregator.property'),
        ),
    ]
