# Generated by Django 4.2.7 on 2023-11-29 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_component_property_remove_casefan_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='component_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='label',
        ),
        migrations.AddField(
            model_name='offer',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aggregator.component'),
        ),
        migrations.AddField(
            model_name='property',
            name='value',
            field=models.JSONField(null=True),
        ),
    ]
