# Generated by Django 4.2.7 on 2023-11-29 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_remove_component_properties_property_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='aggregator.component'),
        ),
        migrations.AlterField(
            model_name='property',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='aggregator.component'),
        ),
    ]
