# Generated by Django 4.2.7 on 2023-12-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0007_alter_property_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.CharField(choices=[('processor', 'Процессор'), ('motherboard', 'Материнская плата'), ('graphicsCard', 'Видеокарта'), ('ram', 'ОЗУ'), ('cooler', 'Кулер'), ('caseFan', 'Вентилятор'), ('liquidCooling', 'Жидкостное охлаждение'), ('case', 'Корпус'), ('hdd', 'Диск HDD'), ('ssd', 'Диск SSD'), ('ssdm2', 'Диск SSDM2'), ('powerSupply', 'Блок питания')], max_length=50),
        ),
    ]
