# Generated by Django 4.2.7 on 2023-12-11 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0009_componenttype_remove_property_component_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyvalue',
            name='component',
        ),
        migrations.RemoveField(
            model_name='propertyvalue',
            name='property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='component_type',
        ),
        migrations.AddField(
            model_name='property',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='aggregator.component'),
        ),
        migrations.AddField(
            model_name='property',
            name='value',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.CharField(choices=[('processor', 'Процессор'), ('motherboard', 'Материнская плата'), ('graphicsCard', 'Видеокарта'), ('ram', 'ОЗУ'), ('cooler', 'Кулер'), ('caseFan', 'Вентилятор'), ('liquidCooling', 'Жидкостное охлаждение'), ('case', 'Корпус'), ('hdd', 'Диск HDD'), ('ssd', 'Диск SSD'), ('ssdm2', 'Диск SSDM2'), ('powerSupply', 'Блок питания')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ComponentType',
        ),
        migrations.DeleteModel(
            name='PropertyValue',
        ),
    ]
