# Generated by Django 4.2.7 on 2023-12-11 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0010_remove_propertyvalue_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='component',
        ),
        migrations.RemoveField(
            model_name='property',
            name='value',
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.component')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='component_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aggregator.componenttype'),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.componenttype'),
        ),
    ]
