# Generated by Django 4.2.7 on 2023-12-11 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0011_componenttype_remove_property_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='component_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='aggregator.componenttype'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='aggregator.component'),
        ),
    ]
