# Generated by Django 4.2.7 on 2024-01-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0012_alter_property_component_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenttype',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
