# Generated by Django 4.2.7 on 2024-01-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0013_componenttype_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenttype',
            name='search_tags',
            field=models.TextField(null=True),
        ),
    ]
