# Generated by Django 4.2.7 on 2024-01-21 07:47

import aggregator.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0015_pg_trgm_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='logo_height',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='logo_width',
        ),
        migrations.RemoveField(
            model_name='store',
            name='logo_height',
        ),
        migrations.RemoveField(
            model_name='store',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='store',
            name='logo_width',
        ),
        migrations.CreateModel(
            name='StoreLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('file', models.ImageField(height_field='height', upload_to=aggregator.models.get_store_logo_url, width_field='width')),
                ('store', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='aggregator.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManufacturerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('file', models.ImageField(height_field='height', upload_to=aggregator.models.get_manufacturer_logo_url, width_field='width')),
                ('manufacturer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='aggregator.manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('file', models.ImageField(height_field='height', upload_to=aggregator.models.get_component_picture_url, width_field='width')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='aggregator.component')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
