# Generated by Django 4.2.7 on 2024-02-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0017_propertycategory_property_property_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componenttype',
            old_name='name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='componenttype',
            old_name='label',
            new_name='name',
        ),
    ]
