# Generated by Django 4.2.7 on 2024-02-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0020_alter_componenttype_search_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='component_type',
        ),
        migrations.AddField(
            model_name='property',
            name='order',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='component_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_categories', to='aggregator.componenttype'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='order',
            field=models.FloatField(null=True),
        ),
    ]
