# Generated by Django 4.2.7 on 2024-02-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0023_alter_property_order_alter_propertycategory_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycategory',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_categories', to='aggregator.componenttype'),
        ),
    ]
