# Generated by Django 4.2.7 on 2024-02-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0024_alter_propertycategory_component_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
