# Generated by Django 4.2.7 on 2024-02-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0025_property_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.CharField(max_length=50),
        ),
    ]
