# Generated by Django 4.2.7 on 2024-02-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0027_alter_property_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyvalue',
            old_name='property',
            new_name='property_proto',
        ),
    ]
