# Generated by Django 4.2.7 on 2024-02-27 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0028_rename_property_propertyvalue_property_proto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='order',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='order',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='property_proto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='aggregator.property'),
        ),
    ]
