# Generated by Django 4.2.7 on 2024-03-01 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0029_alter_property_order_alter_propertycategory_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPossibleValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('property_proto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_values', to='aggregator.property')),
            ],
        ),
    ]
