# Generated by Django 4.2.7 on 2024-03-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0030_propertypossiblevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='multiple_values',
            field=models.BooleanField(default=False),
        ),
    ]
