# Generated by Django 4.2.7 on 2024-03-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0032_remove_propertyvalue_component_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComponentProperty',
            new_name='Property',
        ),
    ]
