# Generated by Django 4.2.7 on 2024-03-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0034_alter_propertyproto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyproto',
            name='multiple_values',
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
