# Generated by Django 4.2.7 on 2024-03-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0035_remove_propertyproto_multiple_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='buy_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PropertyPossibleValue',
        ),
    ]
