# Generated by Django 4.2.7 on 2024-03-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0037_remove_component_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturerlogo',
            name='manufacturer',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='ManufacturerLogo',
        ),
    ]
