# Generated by Django 4.2.7 on 2024-03-08 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0039_propertyproto_is_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyvalue',
            name='component_property',
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='component_properties',
            field=models.ManyToManyField(related_name='values', to='aggregator.property'),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='property_proto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='aggregator.propertyproto'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='value',
            field=models.JSONField(unique=True),
        ),
    ]
