# Generated by Django 4.2.7 on 2024-03-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0042_alter_propertyvalue_property_proto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingPropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('property_proto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='aggregator.propertyproto')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyValuePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_value_pairs', to='aggregator.property')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_value_pairs', to='aggregator.existingpropertyvalue')),
            ],
        ),
        migrations.DeleteModel(
            name='PropertyValue',
        ),
        migrations.AddConstraint(
            model_name='existingpropertyvalue',
            constraint=models.UniqueConstraint(fields=('property_proto', 'value'), name='unique_property_value'),
        ),
    ]
