# Generated by Django 4.2.7 on 2024-03-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0044_existingpropertyvalue_props'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyvaluepair',
            old_name='value',
            new_name='existing_property_value',
        ),
    ]
