# Generated by Django 4.2.7 on 2024-03-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0045_rename_value_propertyvaluepair_existing_property_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='existingpropertyvalue',
            options={'ordering': ('order', 'value')},
        ),
        migrations.AddField(
            model_name='existingpropertyvalue',
            name='order',
            field=models.FloatField(default=0),
        ),
    ]
