# Generated by Django 4.2.7 on 2024-03-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0046_alter_existingpropertyvalue_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='propertyproto',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='unique_property_proto'),
        ),
    ]
