# Generated by Django 4.2.7 on 2024-03-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0047_propertyproto_unique_property_proto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyproto',
            name='slug',
            field=models.CharField(max_length=50),
        ),
    ]
