# Generated by Django 4.2.7 on 2024-03-22 09:53

import aggregator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0050_componenttype_is_multiple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentpicture',
            name='file',
            field=models.ImageField(height_field='height', max_length=200, upload_to=aggregator.models.get_component_picture_url, width_field='width'),
        ),
    ]
