# Generated by Django 4.2.7 on 2024-03-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0052_alter_component_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncompatibleProcessorChipset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chipset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.existingpropertyvalue')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.component')),
            ],
        ),
        migrations.AddField(
            model_name='existingpropertyvalue',
            name='incompatible_processors',
            field=models.ManyToManyField(related_name='incompatible_chipsets', through='aggregator.IncompatibleProcessorChipset', to='aggregator.component'),
        ),
    ]
