# Generated by Django 4.2.7 on 2024-04-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aggregator", "0053_incompatibleprocessorchipset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="incompatible_with",
            field=models.ManyToManyField(to="aggregator.component"),
        ),
    ]
