# Generated by Django 4.2.7 on 2024-04-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("aggregator", "0057_alter_component_incompatible_with"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncompatibleProcessorCooler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aggregator.component",
                    ),
                ),
                (
                    "tdp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aggregator.existingpropertyvalue",
                    ),
                ),
            ],
        ),
    ]
