# Generated by Django 4.2.7 on 2024-04-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aggregator", "0058_incompatibleprocessorcooler"),
    ]

    operations = [
        migrations.AddField(
            model_name="existingpropertyvalue",
            name="incompatible_processors_by_cooler",
            field=models.ManyToManyField(
                related_name="incompatible_cooler_tdp",
                through="aggregator.IncompatibleProcessorCooler",
                to="aggregator.component",
            ),
        ),
    ]
