# Generated by Django 4.2.7 on 2024-04-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aggregator", "0059_existingpropertyvalue_incompatible_processors_by_cooler"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="existingpropertyvalue",
            name="incompatible_processors_by_cooler",
        ),
        migrations.AlterField(
            model_name="incompatibleprocessorcooler",
            name="tdp",
            field=models.IntegerField(),
        ),
    ]
