# Generated by Django 4.2.7 on 2024-04-18 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "aggregator",
            "0060_remove_existingpropertyvalue_incompatible_processors_by_cooler_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="existingpropertyvalue",
            name="comparison_value",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="incompatibleprocessorcooler",
            name="processor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incompatible_coolers",
                to="aggregator.component",
            ),
        ),
    ]
