# Generated by Django 4.2.7 on 2024-04-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("aggregator", "0062_alter_incompatibleprocessorcooler_processor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incompatibleprocessorcooler",
            name="processor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incompatible_coolers",
                to="aggregator.component",
            ),
        ),
    ]
