# Generated by Django 4.2.7 on 2024-04-21 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aggregator", "0063_alter_incompatibleprocessorcooler_processor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incompatibleprocessorcooler",
            name="tdp",
        ),
    ]
