# Generated by Django 4.2.7 on 2024-04-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aggregator", "0064_remove_incompatibleprocessorcooler_tdp"),
    ]

    operations = [
        migrations.AddField(
            model_name="incompatibleprocessorcooler",
            name="tdp",
            field=models.IntegerField(default=0),
        ),
    ]
