# Generated by Django 4.2.7 on 2024-04-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aggregator", "0065_incompatibleprocessorcooler_tdp"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="warnings",
            field=models.ManyToManyField(blank=True, to="aggregator.component"),
        ),
        migrations.AlterField(
            model_name="existingpropertyvalue",
            name="comparison_value",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
