# Generated by Django 4.2.7 on 2024-05-06 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aggregator", "0066_component_warnings_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={"ordering": ["price"]},
        ),
    ]
