# Generated by Django 4.2.7 on 2024-05-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aggregator", "0068_propertyproto_is_short"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyproto",
            name="is_short",
            field=models.BooleanField(default=False),
        ),
    ]
