# Generated by Django 4.2.7 on 2024-05-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aggregator", "0069_alter_propertyproto_is_short"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                ("token", models.CharField(primary_key=True, serialize=False)),
            ],
        ),
    ]
