# Generated by Django 4.2.7 on 2024-06-07 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aggregator", "0070_accesstoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccessToken",
        ),
    ]
