# Generated by Django 4.2.7 on 2024-01-30 07:42

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=32)),
                ('contact', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EarlyAccessMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('early_access_token', models.CharField(default=users.models.generate_early_access_token, max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='contact',
            name='early_access_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.earlyaccessmember'),
        ),
    ]
