# Generated by Django 4.2.7 on 2024-01-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contact_earlyaccessmember_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlyaccessmember',
            name='first_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='earlyaccessmember',
            name='last_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
