# Generated by Django 4.2.7 on 2024-01-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_earlyaccessmember_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlyaccessmember',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='earlyaccessmember',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='earlyaccessmember',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
