# Generated by Django 4.2.7 on 2024-01-30 08:34

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_earlyaccessmember_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=users.models.generate_early_access_token, max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='earlyaccessmember',
            name='early_access_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='early_access_members', to='users.earlyaccesstoken'),
        ),
    ]
