# Generated by Django 4.2.7 on 2024-02-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_earlyaccessmember_early_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlyaccessmember',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True),
        ),
    ]
